---

# handlers file for inverso.jenkins

- name: systemctl_daemon-reload
  systemd:
    name: jenkins
    daemon_reload: yes

- name: set owner and permissions for jenkins_home
  file:
    path: '{{ jenkins_home }}'
    state: directory
    owner: '{{jenkins_user}}'
    group: '{{jenkins_group}}'
    recurse: yes

- name: configure default users
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_group }}'
  with_items:
    - src: 'groovy/update_admin_password.groovy.j2'
      dest: '{{ jenkins_home }}/init.groovy.d/10_update_admin_password.groovy'
    - src: 'groovy/configure_csrf.groovy.j2'
      dest: '{{ jenkins_home }}/init.groovy.d/20_configure_csrf.groovy'
  register: jenkins_users_config

- name: restart jenkins
  service:
    name: jenkins
    state: 'restarted'
